### ISSUE TITLE
Have you considered integrating the pushwoosh npm package as well?

### ISSUE THREAD

**Issue by Pushplaybang** [lpender/meteor-pushwoosh#10]
Hey There

Still pretty new to pushwoosh  and push notifications in general but came across your package as well as this npm package:

https://github.com/nluo/pushwoosh-node-client

Would it be beneficial to look at integrating it for the server side?

**Comment by lpender** [comment]
I actually have a branch where I started integrating it, but I didn't really see much benefit. As far as I can see, it provides a little syntactic sugar around wrapping API requests, which I didn't feel I needed.
